# Generated by Django 3.2.18 on 2023-04-04 17:57

import crypto_address.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=crypto_address.utils.generate_uuid)),
                ('address', models.CharField(max_length=64)),
                ('wallet', models.CharField(choices=[('ETH', 'Ethereum'), ('BTC', '15A')], max_length=25, unique=True)),
            ],
        ),
    ]
