# Generated by Django 3.2.18 on 2023-04-05 10:26

import crypto_address.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=crypto_address.utils.generate_uuid)),
                ('private_key', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=crypto_address.utils.generate_uuid)),
                ('address', models.CharField(max_length=64)),
                ('wallet', models.CharField(choices=[('ETH', 'Ethereum'), ('BTC', 'Bitcoin')], max_length=25)),
                ('private_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='crypto_address.walletprivatekey')),
            ],
        ),
    ]
