# Generated by Django 3.2.18 on 2023-04-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_address', '0002_alter_walletaddress_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaddress',
            name='address',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
