# Generated by Django 3.2.18 on 2023-04-05 06:47

import crypto_address.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_address', '0004_alter_walletaddress_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=crypto_address.utils.generate_uuid)),
                ('private_key', models.CharField(max_length=128)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='crypto_address.walletaddress')),
            ],
        ),
    ]
