# Generated by Django 3.2.18 on 2023-04-05 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_address', '0005_walletprivatekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletprivatekey',
            name='wallet',
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='private_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='crypto_address.walletprivatekey'),
            preserve_default=False,
        ),
    ]
